# Autogenerated file
# List of stocks from api

stocks=['quis', 'ip', 'nc', 'ntar', 'hive', 'apha', 'bb', 'hut', 'tbx', 'art', 'myco', 'dsci', 'ampd', 'gblc', 'swis', 'very', 'meat', 'mtrx', 'erth', 'cgx', 'cve', 'ttt', 'acb', 'lspd', 'ac', 'ocft', 'wifi', 'mvis'] 
