name: Testing Modules

on:
  push:
    branches:
      - '*'

env:
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
  GH_PAGES_BRANCH: gh-pages
  MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
  MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}

jobs:
  test_code:
    name: Install Requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.7' # Semantic version range syntax or exact version of a Python version
          architecture: 'x64' # Optional - x64 or x86, defaults to x64
      - name: installation of dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo wget https://github.com/plotly/orca/releases/download/v1.2.1/orca-1.2.1-x86_64.AppImage -O /usr/local/bin/orca
          sudo chmod +x /usr/local/bin/orca
          sudo apt-get install xvfb libgtk2.0-0 libgconf-2-4 tree -y
          python -m spacy download en_core_web_sm
          python -m textblob.download_corpora
      - name: Generate Report Test
        run:  |
          python -m lib.youtube.yt_nlp
      - name: Pull Youtube Channels
        run: |
          python -m lib.youtube.get_videos
          